### ISSUE TITLE
double click needed to open a list of windows

### ISSUE THREAD

**Issue by grgrzybek** [fthx/window-title-is-back#12]
Thanks for this extension - I was surprised that the window title is missing in Gnome 45...

However I used to click on the title (Gnome topbar) to open a list of windows to switch between windows in the same group.

With your extension you have to click twice to see:
![image](https://github.com/fthx/window-title-is-back/assets/306565/34a47062-cdc5-4639-b8cd-af1198a70064)

but even if I see two IDEA windows, I can't move cursor there, because the menu disappears ;(

**Comment by fthx** [comment]
https://github.com/fthx/window-title-is-back/commit/af43b02b8bf2cbff2233ea29ed4f4da381455376

Uploaded to GS extensions website, should be available soon.
I do use Wayland so I missed this one (in X11 I just noticed the double click needed, but the problem was way worse you're right).
Bonus: cleaner code, the active part is now very short.

**Comment by fthx** [comment]
and now it should be ok...
https://github.com/fthx/window-title-is-back/commit/0476bd39fea7735be2d6d5f62694acafe1c1b6bc

**Comment by fthx** [comment]
If you have some time, could you test the latest extension.js code? There are plenty of extensions waiting for review atm.
Thanks!

**Comment by fthx** [comment]
It's online now. Yous should get an update.
